name: disemvowel-main-valgrind

on: push
#    paths:
#    - 'disemvowel/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install valgrind
      run: sudo apt-get install -y valgrind
    - name: Check out the code
      uses: actions/checkout@v2
    - name: Compile code
      run: gcc -Wall -g -o disemvowel disemvowel.c main.c
      working-directory: disemvowel
    - name: Run test
      run: valgrind -v --leak-check=full --show-leak-kinds=all --error-exitcode=1 ./disemvowel < main.c
      working-directory: disemvowel
