name: disemvowel-gtest

on: push
#    paths:
#    - 'disemvowel/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Cache gtest library
      id: cache-gtest
      uses: actions/cache@v3
      env:
        cache-name: cache-gtest-lib
      with:
        key: $${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('~/lib/libgtest.a', '~/lib/libgtest_main.a', '~/include/**/*.h') }}
        path: |
          /usr/lib/libgtest.a
          /usr/lib/libgtest_main.a
          ~/include
        restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
    - if: ${{ steps.cache-gtest.outputs.cache-hit != 'true' }}
      name: Install gtest manually
      run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp lib/*.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
    - name: Check out the code
      uses: actions/checkout@v2
    - name: Compile test code
      run: g++ -Wall -g -o disemvowel_test disemvowel.c disemvowel_test.cpp -I"~/include" -L"~/lib" -lgtest -pthread -std=c++0x
      working-directory: disemvowel
    - name: Run test
      run: ./disemvowel_test
      working-directory: disemvowel

