name: palindrome-test-valgrind

on: push
#    paths:
#    - 'palindrome/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Cache gtest library
      id: cache-gtest
      uses: actions/cache@v3
      env:
        cache-name: cache-gtest-lib
      with:
        key: $${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('~/lib/libgtest.a', '~/lib/libgtest_main.a', '~/include/**/*.h') }}
        path: |
          ~/lib/libgtest.a
          ~/lib/libgtest_main.a
          ~/include
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - if: ${{ steps.cache-gtest.outputs.cache-hit != 'true' }}
      name: Install gtest manually
      run: |
        sudo apt-get install libgtest-dev
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
    - name: Install valgrind
      run: sudo apt-get install -y valgrind
    - name: Check out the code
      uses: actions/checkout@v2
    - name: Compile code
      run: g++ -Wall -g -o palindrome_test palindrome.c palindrome_test.cpp -I"~/include" -L"~/lib" -lgtest -pthread -std=c++0x
      working-directory: palindrome
    - name: Run test
      run: valgrind -v --leak-check=full --show-leak-kinds=all --error-exitcode=1 ./palindrome_test
      working-directory: palindrome
